### ISSUE TITLE
Small UI bug

### ISSUE THREAD

**Issue by ilkome** [ktquez/pickout#17]
Win 8.1 
Chrome 50
![Image](https://vgy.me/NwYqtf.png)

**Comment by ktquez** [comment]
Thanks @ilkome

**Comment by ktquez** [comment]
Do you still view this bug?

**Comment by ilkome** [comment]
Yes, same in latest Firefox DE. 
I have 3200*1800 resolution on 15 inc laptop, maybe it's will help.
