### ISSUE TITLE
Return the multiple selecteds 

### ISSUE THREAD

**Issue by romuloinnocencio** [ktquez/pickout#18]
Hi, sorry if i speak some shit....
But a can't understand how can i get the value of multiple selected input;

**There's a method for this?**

**Comment by ktquez** [comment]
E ai man @romuloinnocencio , blz?
Não sei entendi, mas o múltipla escolha funciona bem quando no campo select colocamos o `[]`  no name, por exemplo:
`<select name="skills[]" id="skills" multiple ...` 

Quando submetido o é possível pegar as opções no servidor.

Não sei se era isso, se não for, me fala, que vamos até concluirmos o raciocínio, blz?

Abraço e vlw.

**Comment by romuloinnocencio** [comment]
Eu estou usando o Pickout para fazer um filtro de imóveis, então, no meu caso... eu quero saber quais cidades a pessoa escolheu no select, e vou passar no url. Como faço para identificar? Eu não entendi como fazer.... eu não chego a dar um submit, apenar faço um location.href passando os dados selecionados na query.

**Comment by romuloinnocencio** [comment]
Consegui aqui mano, foi mais simples do que eu pensava... eu que não havia testado direito.....
simplesmente fiz **document.getelementbyid().value**; e ele já retornou um array. Ignore meu noobismo hahaha.

**Comment by ktquez** [comment]
@romuloinnocencio 
Ahh man, blz
Tá tranquilo, ainda bem que conseguiu.

Precisando é só falar.
