### ISSUE TITLE
Setar selecionados anteriormente

### ISSUE THREAD

**Issue by romuloinnocencio** [ktquez/pickout#19]
Eu salvei os que foram selecionados em um momento anterior em um Array, há como colocá-los como ativos logo queo Pickout iniciar? Para que o 'input' que ele cria, seja preenchido com o nome do item + close;

**Comment by ktquez** [comment]
Opa, Tem sim @romuloinnocencio 
No select, é só marcar as selecionadas por default usando o atributo `selected`
Tipo:

``` html
<select name="..." multiple class="suaClass" placeholder="...">
<option value="opt1">Option 1</option>
<option selected value="op2">Option 2</option>
<option selected  value="opt3">Option 3</option>
...
```

Utiliza o `pickout.updatedMultiple('.suaClass');`

Para que ele possa pegar os selecionados e montar as tags

**Comment by romuloinnocencio** [comment]
Cara, não sei o que to fazendo ....
**Cannot read property 'children' of null**
Eu marquei os 'selected' dos caras que quero e depois inicio o pickout.updatedMultiple();

**Comment by romuloinnocencio** [comment]
Eu tava dando update sem ter iniciado, achando que o update já o fazia. =/

**Comment by ktquez** [comment]
@romuloinnocencio 
Show de boa man, conseguiu?
Se sim, massa.
